name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'  # 指定你的 Java 版本
          distribution: 'adopt'  # 或者 'temurin', 'zulu', 等

      - name: Create temporary XML config file
        run: |
          TEMP_FILE=$(mktemp)
          echo "${{ secrets.UT_CONF }}" > "$TEMP_FILE"
          echo "TEMP_FILE=$TEMP_FILE" >> $GITHUB_ENV  # 将临时文件路径注入环境变量

      - name: Run tests
        run: mvn test -Dconfig.file="$TEMP_FILE"  # 使用临时文件路径

      - name: Clean up
        run: rm "$TEMP_FILE"  # 删除临时文件